baseURL = "https://yourdomain.com/"
languageCode = "en-us"
title = "Ashish Jingar's Portfoli-Go"

[params]
  author = "Ashish Jingar"
  description = "Associate Consultant at OFSS"
  github = "https://github.com/StrangeAJ" 
  socialIcons = "outlined"
  theme = "light"
  linkedin = "https://www.linkedin.com/in/jingar-ashish"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3
  
  [[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/work/"
    weight = 4

