baseURL = "https://yourdomain.com/"
languageCode = "en-us"
title = "Ashish Jingar's Portfoli-Go"

[params]
  author = "Ashish Jingar"
  description = "Associate Consultant at OFSS"
  github = "https://github.com/StrangeAJ" 
  socialIcons = "outlined"
  theme = "light"
  linkedin = "https://www.linkedin.com/in/jingar-ashish"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 1
    
  
  [[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/work/"
    weight = 2


  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3


  [[menu.main]]
    identifier = "skills"
    name = "Skills"
    url = "/skills/"
    weight = 4

  [[menu.main]]
    identifier = "edu"
    name = "Education & Certifications"
    url = "/edu/"
    weight = 5


